// Code generated by tygo. DO NOT EDIT.
// Copyright 2026 The Forgejo Authors. All rights reserved.
// SPDX-License-Identifier: GPL-3.0-or-later
//
// Generated by next/tools/gen-protocol.sh from services/livesync/protocol:
// change the Go types and re-run the script (--check verifies it in CI).

/** A message a client sends (services/livesync/protocol/messages.go). */
export type ClientMessage = HelloMessage | SubscribeMessage | UnsubscribeMessage | BarrierMessage | PingMessage;
/** A message the server sends, discriminated by `type`. */
export type ServerMessage =
  | WelcomeMessage | SubscribedMessage | DeltaMessage | CaughtUpMessage | BootstrapRequiredMessage
  | GroupRevokedMessage | BarrierOKMessage | SessionInvalidMessage | NoticeMessage | PongMessage
  | GrantsMessage | ResumeFromCursorMessage | ErrorMessage | SessionMessage;
/** Why a requested group was refused (Refusal.reason). */
export type RefusalReason = typeof RefusedForbidden | typeof RefusedLimit;
/** Why a group must be loaded again (BootstrapRequiredMessage.reason). */
export type BootstrapReason =
  | typeof BootstrapCursorTrimmed | typeof BootstrapReplayTooLong | typeof BootstrapPermissionChanged
  | typeof BootstrapCursorUnknown | typeof RebootstrapTriggerRepaired | typeof RebootstrapPlacementChanged;
/** NoticeMessage.kind. */
export type NoticeKind = typeof NoticeNewBuild | typeof NoticeShutdown;
/** ErrorMessage.code. */
export type ErrorCode =
  | typeof ErrorBadMessage | typeof ErrorHelloRequired | typeof ErrorTooManyBarriers
  | typeof ErrorTooManyConnections | typeof ErrorInternal;

//////////
// source: bootstrap.go

/**
 * TierFull: every entity of the group (every group but repo:{id}, and
 * issue:{id} also through /-/sync/load).
 */
export const TierFull = "full";
/**
 * TierSummary: a repo:{id} group's summary tier: open issues and pull
 * requests plus those updated since BootstrapHeader.ClosedBefore, with
 * their labels, assignees, pull requests and project cards; commit
 * statuses and action runs updated since then; and every other entity of
 * the group (repository, units, labels, milestones, projects, branches,
 * releases, collaborations).
 */
export const TierSummary = "summary";
/**
 * TierClosed: a page of a repo:{id} group's older closed issues and pull
 * requests (closed, not updated since the summary's cutoff), newest
 * first, with their labels, assignees, pull requests and project cards
 * (GET /-/sync/load?group=repo:{id}&closedBefore=…).
 */
export const TierClosed = "closed";
/**
 * BootstrapHeader is the first line of a bootstrap or load response.
 * Bootstraps and partial loads (PLAN §4.7): GET /-/sync/bootstrap?group=…
 * and GET /-/sync/load?group=… stream NDJSON, one JSON object per line:
 *  1. a BootstrapHeader (type "header");
 *  2. the entities, each a Change with op U (exactly as a delta carries it;
 *     every change's v is the header's watermark). The group's own entities
 *     come first (g = the requested group); they may be followed by the
 *     User entities (profiles) of other groups that the group's entities
 *     refer to (see BootstrapEnd.Refs);
 *  3. a BootstrapEnd (type "end"). A response without it is incomplete
 *     (the server failed or the connection broke): discard it and retry.
 * The watermark is the sync log head read before the snapshot. Subscribe the
 * group with since = watermark (or keep the subscription you have): the
 * stream replays everything after it, and changes apply only when their v is
 * newer than what the client holds, so the overlap is harmless.
 * A full or summary bootstrap (BootstrapHeader.Tier TierFull/TierSummary)
 * replaces what the client holds of the group: once the end line arrived,
 * drop every entity of the group (of the header's Models when it lists
 * some) with a version at or below the watermark that the response did not
 * contain. A closed page (TierClosed) only adds entities, and so do the
 * profile lines of other groups (they are not a bootstrap of those groups).
 * The response is filtered by the viewer's units in the group, which the
 * header states (Units, as in a Grant): keep them with the group and treat a
 * later grant with other units as bootstrap_required{permission_changed}
 * (the units rule, see GroupRequest).
 * An issue's load (issue:{id}) also carries the comments that refer to the
 * issue from other repositories and that the viewer may see (upstream shows
 * them only to readers of the referencing repository's issues or pull
 * requests). They are decided per viewer and are not in the sync log: no
 * delta changes them; the next load of the issue refreshes them.
 */
export interface BootstrapHeader {
  type: 'header';
  group: string;
  /**
   * Watermark is the sync log head read before the snapshot was taken.
   */
  watermark: number /* int64 */;
  /**
   * Units are the viewer's units in the group the response was filtered
   * by (canonical order, as in a Grant).
   */
  units: Unit[];
  /**
   * Tier is TierFull, TierSummary or TierClosed.
   */
  tier: 'full' | 'summary' | 'closed';
  /**
   * Schemas are the schema versions of the models the response may
   * contain (User included: profiles may follow the entities).
   */
  schemas: { [key: Model]: number /* int */};
  /**
   * Models is set when the request asked for some models only (?model=);
   * the response then replaces only those.
   */
  models?: Model[];
  /**
   * ClosedBefore (summary tier) is the recency cutoff, in Unix seconds:
   * closed issues and pull requests not updated since are not in the
   * summary; load them with /-/sync/load?group=…&closedBefore=<this>.
   */
  closed_before?: number /* int64 */;
}
/**
 * BootstrapEnd is the last line of a complete bootstrap or load response.
 */
export interface BootstrapEnd {
  type: 'end';
  /**
   * Count is the number of entities of the requested group sent.
   */
  count: number /* int */;
  /**
   * Refs are the groups holding the User entities (profiles) that the
   * group's entities refer to (posters, assignees, owners, …) and that
   * the viewer may read: the profile directories (profiles:public,
   * profiles:limited), private users' profile:{id} and organizations'
   * org:{id}. The profiles of profile:{id} and org:{id} groups were sent
   * in this response (after the group's own entities); those of the
   * directories were not: subscribe/bootstrap the directories (the
   * workspace does). Subscribe any of them with since = watermark to keep
   * the embedded profiles current.
   */
  refs: string[];
  /**
   * Next (closed tier) is the closedBefore value of the next page; absent
   * on the last page.
   */
  next?: string;
}
/**
 * Workspace answers GET /-/sync/workspace: the groups the client should keep
 * subscribed and bootstrapped (available offline), PLAN §4.7: the viewer's
 * own groups, the profile directories, their organizations and the
 * repositories they own, were given access to or watch — the repositories
 * ordered by recent activity and capped. Other groups (other public
 * repositories, issues) are loaded on demand; a client may pin more itself.
 */
export interface Workspace {
  viewer_id: number /* int64 */;
  groups: WorkspaceGroup[];
  /**
   * Truncated says that repositories were left out because of the cap
   * (MaxRepos, [livesync] WORKSPACE_MAX_REPOS).
   */
  truncated: boolean;
  max_repos: number /* int */;
}
/**
 * WorkspaceGroup is a group of the workspace, with the viewer's units in it
 * (as in a Grant) and why it is there.
 */
export interface WorkspaceGroup {
  group: string;
  units: Unit[];
  reason: 'self' | 'profile' | 'directory' | 'member' | 'owner' | 'access' | 'watch';
}
/**
 * WorkspaceSelf: the viewer's own user:{id} group.
 */
export const WorkspaceSelf = "self";
/**
 * WorkspaceProfile: the viewer's own profile:{id} group.
 */
export const WorkspaceProfile = "profile";
/**
 * WorkspaceDirectory: a shared profile directory.
 */
export const WorkspaceDirectory = "directory";
/**
 * WorkspaceMember: an organization the viewer is a member of.
 */
export const WorkspaceMember = "member";
/**
 * WorkspaceOwner: a repository the viewer owns.
 */
export const WorkspaceOwner = "owner";
/**
 * WorkspaceAccess: a repository the viewer was given access to
 * (collaboration, team, organization ownership).
 */
export const WorkspaceAccess = "access";
/**
 * WorkspaceWatch: a repository the viewer watches (and may read).
 */
export const WorkspaceWatch = "watch";

//////////
// source: entities.go

/**
 * Repository is a repository (group repo:{id}, unit none).
 */
export interface Repository {
  id: number /* int64 */;
  owner_id: number /* int64 */;
  owner_name: string;
  name: string;
  full_name: string;
  description: string;
  website: string;
  private: boolean;
  fork: boolean;
  parent_id: number /* int64 */;
  template: boolean;
  mirror: boolean;
  archived: boolean;
  empty: boolean;
  default_branch: string;
  stars_count: number /* int */;
  forks_count: number /* int */;
  watchers_count: number /* int */;
  topics: string[];
  object_format_name: string;
  avatar_url: string;
  created_at: string /* RFC 3339, UTC */;
  updated_at: string /* RFC 3339, UTC */;
  archived_at?: string /* RFC 3339, UTC */;
}
/**
 * User is the public profile of a user or organization: group
 * profiles:public or profiles:limited for an individual user with that
 * visibility, profile:{id} for a private one, org:{id} for an organization
 * (unit none). Email addresses, admin/active/restricted flags and settings
 * are never included.
 */
export interface User {
  id: number /* int64 */;
  login: string;
  full_name: string;
  avatar_url: string;
  type: string; // "user", "organization", "bot", "remote", "reserved"
  visibility: string; // "public", "limited", "private"
  description: string;
  website: string;
  location: string;
  /**
   * Pronouns is empty when the user keeps them private.
   */
  pronouns: string;
  created_at: string /* RFC 3339, UTC */;
}
/**
 * OrgUser is an organization membership (group org:{org_id}; unit members
 * for a concealed membership).
 */
export interface OrgUser {
  id: number /* int64 */;
  org_id: number /* int64 */;
  user_id: number /* int64 */;
  public: boolean;
}
/**
 * Team is an organization team (group org:{org_id}, unit members).
 */
export interface Team {
  id: number /* int64 */;
  org_id: number /* int64 */;
  name: string;
  description: string;
  permission: string; // "none", "read", "write", "admin", "owner"
  includes_all_repositories: boolean;
  can_create_org_repo: boolean;
  num_members: number /* int */;
  num_repos: number /* int */;
}
/**
 * TeamUser is a team membership (group org:{org_id}, unit members).
 */
export interface TeamUser {
  id: number /* int64 */;
  org_id: number /* int64 */;
  team_id: number /* int64 */;
  user_id: number /* int64 */;
}
/**
 * TeamRepo gives a team access to a repository (group org:{org_id}, unit
 * members).
 */
export interface TeamRepo {
  id: number /* int64 */;
  org_id: number /* int64 */;
  team_id: number /* int64 */;
  repo_id: number /* int64 */;
}
/**
 * TeamUnit is a team's access mode for one unit type (group org:{org_id},
 * unit members).
 */
export interface TeamUnit {
  id: number /* int64 */;
  org_id: number /* int64 */;
  team_id: number /* int64 */;
  type: Unit;
  permission: string;
}
/**
 * Collaboration makes a user a collaborator of a repository (group
 * repo:{repo_id}).
 */
export interface Collaboration {
  id: number /* int64 */;
  repo_id: number /* int64 */;
  user_id: number /* int64 */;
  permission: string;
  created_at: string /* RFC 3339, UTC */;
  updated_at: string /* RFC 3339, UTC */;
}
/**
 * Access is a user's computed access mode to a repository (group
 * user:{user_id}, unit self).
 */
export interface Access {
  id: number /* int64 */;
  user_id: number /* int64 */;
  repo_id: number /* int64 */;
  permission: string;
}
/**
 * RepoUnit is an enabled unit of a repository with its configuration
 * (group repo:{repo_id}).
 */
export interface RepoUnit {
  id: number /* int64 */;
  repo_id: number /* int64 */;
  type: Unit;
  config: { [key: string]: any};
  /**
   * DefaultPermissions: "", "read" or "write" (for everyone signed in).
   */
  default_permissions: string;
  created_at: string /* RFC 3339, UTC */;
}
/**
 * Label is a repository label (group repo:{repo_id}, unit issues|pulls) or
 * an organization label (group org:{org_id}).
 */
export interface Label {
  id: number /* int64 */;
  repo_id: number /* int64 */;
  org_id: number /* int64 */;
  name: string;
  exclusive: boolean;
  description: string;
  color: string;
  num_issues: number /* int */;
  num_closed_issues: number /* int */;
  created_at: string /* RFC 3339, UTC */;
  updated_at: string /* RFC 3339, UTC */;
  archived_at?: string /* RFC 3339, UTC */;
}
/**
 * Milestone is a repository milestone (group repo:{repo_id}, unit
 * issues|pulls).
 */
export interface Milestone {
  id: number /* int64 */;
  repo_id: number /* int64 */;
  title: string;
  description: string;
  state: string; // "open", "closed"
  open_issues: number /* int */;
  closed_issues: number /* int */;
  due_on?: string /* RFC 3339, UTC */;
  closed_at?: string /* RFC 3339, UTC */;
  created_at: string /* RFC 3339, UTC */;
  updated_at: string /* RFC 3339, UTC */;
}
/**
 * Project is a project board of a repository (group repo:{repo_id}, unit
 * projects), of an organization (group org:{owner_id}) or of a user (group
 * profile:{owner_id}).
 */
export interface Project {
  id: number /* int64 */;
  title: string;
  description: string;
  owner_id: number /* int64 */;
  repo_id: number /* int64 */;
  creator_id: number /* int64 */;
  closed: boolean;
  template_type: number /* int */;
  card_type: number /* int */;
  type: number /* int */; // 1 individual, 2 repository, 3 organization
  created_at: string /* RFC 3339, UTC */;
  updated_at: string /* RFC 3339, UTC */;
  closed_at?: string /* RFC 3339, UTC */;
}
/**
 * ProjectColumn is a column of a project board (the project's group).
 */
export interface ProjectColumn {
  id: number /* int64 */;
  project_id: number /* int64 */;
  title: string;
  default: boolean;
  sorting: number /* int */;
  color: string;
  creator_id: number /* int64 */;
  created_at: string /* RFC 3339, UTC */;
  updated_at: string /* RFC 3339, UTC */;
}
/**
 * ProjectIssue places an issue on a project board (group repo:{repo_id} of
 * the issue, unit issues or pulls: a user or organization project can hold
 * issues of repositories its readers cannot see).
 */
export interface ProjectIssue {
  id: number /* int64 */;
  issue_id: number /* int64 */;
  project_id: number /* int64 */;
  column_id: number /* int64 */;
  sorting: number /* int64 */;
}
/**
 * Issue is the summary of an issue or pull request (group repo:{repo_id},
 * unit issues or pulls). Its body is the IssueBody entity of issue:{id}.
 */
export interface Issue {
  id: number /* int64 */;
  repo_id: number /* int64 */;
  number: number /* int64 */;
  poster_id: number /* int64 */;
  original_author: string;
  original_author_id: number /* int64 */;
  title: string;
  content_version: number /* int */;
  milestone_id: number /* int64 */;
  priority: number /* int */;
  state: string; // "open", "closed"
  is_pull: boolean;
  comments: number /* int */;
  ref: string;
  pin_order: number /* int */;
  is_locked: boolean;
  due_date?: string /* RFC 3339, UTC */;
  created_at: string /* RFC 3339, UTC */;
  updated_at: string /* RFC 3339, UTC */;
  closed_at?: string /* RFC 3339, UTC */;
}
/**
 * IssueBody is the description of an issue or pull request (group
 * issue:{id}, same id as the Issue).
 */
export interface IssueBody {
  id: number /* int64 */;
  repo_id: number /* int64 */;
  body: string;
  body_html: string;
  content_version: number /* int */;
}
/**
 * IssueLabel puts a label on an issue (the issue's repo:{repo_id} group).
 */
export interface IssueLabel {
  id: number /* int64 */;
  issue_id: number /* int64 */;
  label_id: number /* int64 */;
}
/**
 * IssueAssignee assigns a user to an issue (the issue's repo:{repo_id}
 * group).
 */
export interface IssueAssignee {
  id: number /* int64 */;
  issue_id: number /* int64 */;
  assignee_id: number /* int64 */;
}
/**
 * PullRequest is the pull-request part of an issue (group
 * repo:{base_repo_id}, unit pulls).
 */
export interface PullRequest {
  id: number /* int64 */;
  issue_id: number /* int64 */;
  number: number /* int64 */;
  status: string; // "conflict", "checking", "mergeable", "manually_merged", "error", "empty", "ancestor"
  head_repo_id: number /* int64 */;
  base_repo_id: number /* int64 */;
  head_branch: string;
  base_branch: string;
  merge_base: string;
  allow_maintainer_edit: boolean;
  merged: boolean;
  merge_commit_sha: string;
  merger_id: number /* int64 */;
  merged_at?: string /* RFC 3339, UTC */;
  commits_ahead: number /* int */;
  commits_behind: number /* int */;
  conflicted_files: string[];
  flow: number /* int */; // 0 branches, 1 AGit
}
/**
 * AutoMerge schedules a pull request to be merged when its checks pass (the
 * pull request's group, unit pulls).
 */
export interface AutoMerge {
  id: number /* int64 */;
  pull_id: number /* int64 */;
  doer_id: number /* int64 */;
  merge_style: string;
  delete_branch_after_merge: boolean;
  created_at: string /* RFC 3339, UTC */;
}
/**
 * Branch is a branch and its head commit (group repo:{repo_id}, unit code).
 */
export interface Branch {
  id: number /* int64 */;
  repo_id: number /* int64 */;
  name: string;
  commit_id: string;
  commit_message: string;
  commit_time: string /* RFC 3339, UTC */;
  pusher_id: number /* int64 */;
  is_deleted: boolean;
  deleted_by_id: number /* int64 */;
  deleted_at?: string /* RFC 3339, UTC */;
  created_at: string /* RFC 3339, UTC */;
  updated_at: string /* RFC 3339, UTC */;
}
/**
 * Release is a release (group repo:{repo_id}, unit releases) or a tag
 * without a release (is_tag; unit code, like API v1's /tags). Draft
 * releases are in no group (upstream shows them to writers only): they
 * appear when published.
 */
export interface Release {
  id: number /* int64 */;
  repo_id: number /* int64 */;
  publisher_id: number /* int64 */;
  tag_name: string;
  target_commitish: string;
  name: string;
  sha: string;
  body: string;
  body_html: string;
  draft: boolean;
  prerelease: boolean;
  is_tag: boolean;
  num_commits: number /* int64 */;
  hide_archive_links: boolean;
  original_author: string;
  created_at: string /* RFC 3339, UTC */;
}
/**
 * CommitStatus is one status reported for a commit (group repo:{repo_id},
 * unit code).
 */
export interface CommitStatus {
  id: number /* int64 */;
  repo_id: number /* int64 */;
  index: number /* int64 */;
  state: string; // "pending", "success", "error", "failure", "warning"
  sha: string;
  target_url: string;
  description: string;
  context: string;
  creator_id: number /* int64 */;
  created_at: string /* RFC 3339, UTC */;
  updated_at: string /* RFC 3339, UTC */;
}
/**
 * ActionRun is a workflow run (group repo:{repo_id}, unit actions).
 */
export interface ActionRun {
  id: number /* int64 */;
  repo_id: number /* int64 */;
  owner_id: number /* int64 */;
  title: string;
  workflow_id: string;
  run_number: number /* int64 */;
  trigger_user_id: number /* int64 */;
  ref: string;
  commit_sha: string;
  event: string;
  trigger_event: string;
  status: string;
  is_fork_pull_request: boolean;
  pull_request_id: number /* int64 */;
  need_approval: boolean;
  approved_by: number /* int64 */;
  started?: string /* RFC 3339, UTC */;
  stopped?: string /* RFC 3339, UTC */;
  created_at: string /* RFC 3339, UTC */;
  updated_at: string /* RFC 3339, UTC */;
}
/**
 * ActionRunJob is a job of a workflow run (group repo:{repo_id}, unit
 * actions).
 */
export interface ActionRunJob {
  id: number /* int64 */;
  run_id: number /* int64 */;
  repo_id: number /* int64 */;
  owner_id: number /* int64 */;
  commit_sha: string;
  name: string;
  attempt: number /* int64 */;
  job_id: string;
  needs: string[];
  runs_on: string[];
  task_id: number /* int64 */;
  status: string;
  started?: string /* RFC 3339, UTC */;
  stopped?: string /* RFC 3339, UTC */;
  created_at: string /* RFC 3339, UTC */;
  updated_at: string /* RFC 3339, UTC */;
}
/**
 * Notification is an inbox entry of a user (group user:{user_id}, unit
 * self).
 */
export interface Notification {
  id: number /* int64 */;
  user_id: number /* int64 */;
  repo_id: number /* int64 */;
  status: string; // "unread", "read", "pinned"
  subject: string; // "issue", "pull", "commit", "repository"
  issue_id: number /* int64 */;
  comment_id: number /* int64 */;
  created_at: string /* RFC 3339, UTC */;
  updated_at: string /* RFC 3339, UTC */;
}
/**
 * Stopwatch is a user's running time tracker on an issue (group
 * user:{user_id}, unit self).
 */
export interface Stopwatch {
  id: number /* int64 */;
  user_id: number /* int64 */;
  issue_id: number /* int64 */;
  created_at: string /* RFC 3339, UTC */;
}
/**
 * IssueWatch is a user's explicit (un)subscription to an issue (group
 * user:{user_id}, unit self).
 */
export interface IssueWatch {
  id: number /* int64 */;
  user_id: number /* int64 */;
  issue_id: number /* int64 */;
  is_watching: boolean;
  created_at: string /* RFC 3339, UTC */;
  updated_at: string /* RFC 3339, UTC */;
}
/**
 * Watch is a user's watch settings for a repository (group user:{user_id},
 * unit self).
 */
export interface Watch {
  id: number /* int64 */;
  user_id: number /* int64 */;
  repo_id: number /* int64 */;
  automatic: boolean;
  issues: boolean;
  pull_requests: boolean;
  releases: boolean;
  created_at: string /* RFC 3339, UTC */;
  updated_at: string /* RFC 3339, UTC */;
}
/**
 * Star is a user's star on a repository (group user:{user_id}, unit self).
 */
export interface Star {
  id: number /* int64 */;
  user_id: number /* int64 */;
  repo_id: number /* int64 */;
  created_at: string /* RFC 3339, UTC */;
}
/**
 * BlockedUser records that user_id blocked block_id (group user:{user_id},
 * unit self).
 */
export interface BlockedUser {
  id: number /* int64 */;
  user_id: number /* int64 */;
  block_id: number /* int64 */;
  created_at: string /* RFC 3339, UTC */;
}
/**
 * Comment is one timeline entry of an issue or pull request: a comment, a
 * code review comment or an event (group issue:{issue_id}, unit issues or
 * pulls). Code comments of a pending review are in the reviewer's group
 * (user:{reviewer_id}, unit self) until the review is submitted;
 * cross-references from another repository are in no group (upstream shows
 * them only to readers of that repository's issues or pulls). Type is Forgejo's comment type name ("comment", "close", "label",
 * "code", ...); the other fields are set as the type uses them.
 */
export interface Comment {
  id: number /* int64 */;
  issue_id: number /* int64 */;
  type: string;
  poster_id: number /* int64 */;
  original_author: string;
  original_author_id: number /* int64 */;
  body: string;
  body_html: string;
  content_version: number /* int */;
  label_id: number /* int64 */;
  old_project_id: number /* int64 */;
  project_id: number /* int64 */;
  old_milestone_id: number /* int64 */;
  milestone_id: number /* int64 */;
  time_id: number /* int64 */;
  assignee_id: number /* int64 */;
  assignee_team_id: number /* int64 */;
  removed_assignee: boolean;
  resolve_doer_id: number /* int64 */;
  old_title: string;
  new_title: string;
  old_ref: string;
  new_ref: string;
  dependent_issue_id: number /* int64 */;
  line: number /* int64 */;
  extra_lines_count: number /* int64 */;
  path: string;
  diff_hunk: string;
  commit_id: string;
  review_id: number /* int64 */;
  invalidated: boolean;
  ref_repo_id: number /* int64 */;
  ref_issue_id: number /* int64 */;
  ref_comment_id: number /* int64 */;
  ref_action: number /* int */;
  ref_is_pull: boolean;
  created_at: string /* RFC 3339, UTC */;
  updated_at: string /* RFC 3339, UTC */;
}
/**
 * Reaction is an emoji reaction on an issue or comment (group
 * issue:{issue_id}, or the group of its comment).
 */
export interface Reaction {
  id: number /* int64 */;
  issue_id: number /* int64 */;
  comment_id: number /* int64 */;
  user_id: number /* int64 */;
  original_author: string;
  content: string;
  created_at: string /* RFC 3339, UTC */;
}
/**
 * Review is a pull request review or review request (group
 * issue:{issue_id}, unit pulls). A pending review is a draft only its
 * reviewer sees: group user:{reviewer_id}, unit self, until submitted.
 */
export interface Review {
  id: number /* int64 */;
  issue_id: number /* int64 */;
  state: string; // "PENDING", "APPROVED", "COMMENT", "REQUEST_CHANGES", "REQUEST_REVIEW"
  reviewer_id: number /* int64 */;
  reviewer_team_id: number /* int64 */;
  original_author: string;
  body: string;
  body_html: string;
  official: boolean;
  commit_id: string;
  stale: boolean;
  dismissed: boolean;
  created_at: string /* RFC 3339, UTC */;
  updated_at: string /* RFC 3339, UTC */;
}
/**
 * ReviewState holds a user's "viewed files" of a pull request at a commit
 * (group user:{user_id}, unit self). Values: 0 unviewed, 1 changed since viewed,
 * 2 viewed.
 */
export interface ReviewState {
  id: number /* int64 */;
  user_id: number /* int64 */;
  pull_id: number /* int64 */;
  commit_sha: string;
  updated_files: { [key: string]: number /* uint8 */};
  updated_at: string /* RFC 3339, UTC */;
}
/**
 * Attachment is a file attached to an issue (group issue:{issue_id}), a
 * comment (the comment's group) or a release (the release's group: repo:{repo_id},
 * unit releases, or none for a draft).
 */
export interface Attachment {
  id: number /* int64 */;
  uuid: string;
  uploader_id: number /* int64 */;
  repo_id: number /* int64 */;
  issue_id: number /* int64 */;
  release_id: number /* int64 */;
  comment_id: number /* int64 */;
  name: string;
  size: number /* int64 */;
  download_count: number /* int64 */;
  external_url: string;
  created_at: string /* RFC 3339, UTC */;
}
/**
 * IssueDependency says issue_id is blocked by dependency_id (group
 * issue:{issue_id}).
 */
export interface IssueDependency {
  id: number /* int64 */;
  user_id: number /* int64 */;
  issue_id: number /* int64 */;
  dependency_id: number /* int64 */;
  created_at: string /* RFC 3339, UTC */;
  updated_at: string /* RFC 3339, UTC */;
}
/**
 * TrackedTime is time a user logged on an issue (group issue:{issue_id}).
 */
export interface TrackedTime {
  id: number /* int64 */;
  issue_id: number /* int64 */;
  user_id: number /* int64 */;
  time: number /* int64 */; // seconds
  deleted: boolean;
  created: string /* RFC 3339, UTC */;
}
/**
 * ContentHistory is one revision of an issue or comment body (group
 * issue:{issue_id}, or the group of its comment). The catalog puts the table
 * in the on-demand tier: the sync log carries the revision's metadata only,
 * the text itself is fetched on request.
 */
export interface ContentHistory {
  id: number /* int64 */;
  poster_id: number /* int64 */;
  issue_id: number /* int64 */;
  comment_id: number /* int64 */;
  edited_at: string /* RFC 3339, UTC */;
  is_first_created: boolean;
  is_deleted: boolean;
}

//////////
// source: messages.go

/**
 * ProtocolVersion is the version of the sync protocol (WelcomeMessage.Protocol).
 * It changes only when a message changes incompatibly; entity DTO changes are
 * versioned per model (the Schema* constants, WelcomeMessage.Schemas).
 */
export const ProtocolVersion = 1;
/**
 * MessageType is the "type" of a protocol message.
 */
export type MessageType = string;
export const MsgHello: MessageType = "hello";
export const MsgSubscribe: MessageType = "subscribe";
export const MsgUnsubscribe: MessageType = "unsubscribe";
export const MsgBarrier: MessageType = "barrier";
export const MsgPing: MessageType = "ping";
export const MsgWelcome: MessageType = "welcome";
export const MsgSubscribed: MessageType = "subscribed";
export const MsgDelta: MessageType = "delta";
export const MsgCaughtUp: MessageType = "caught_up";
export const MsgBootstrapRequired: MessageType = "bootstrap_required";
export const MsgGroupRevoked: MessageType = "group_revoked";
export const MsgBarrierOK: MessageType = "barrier_ok";
export const MsgSessionInvalid: MessageType = "session_invalid";
export const MsgNotice: MessageType = "notice";
export const MsgPong: MessageType = "pong";
export const MsgGrants: MessageType = "grants";
export const MsgResumeFromCursor: MessageType = "resume_from_cursor";
export const MsgError: MessageType = "error";
/**
 * MsgSession is the first event of the fallback transport (SSE): the
 * session id the client sends its messages with.
 */
export const MsgSession: MessageType = "session";
/**
 * GroupRequest asks for a group. Since is the position the client already
 * holds in it (the server replays the entries after it, then streams live
 * ones); without it the subscription starts live at the server's current
 * position (e.g. right after a bootstrap whose watermark is at least that).
 * The answer's Grant carries the viewer's units in the group now. The
 * client keeps with each group the units what it holds was filtered by
 * (those of the grant or the bootstrap that loaded it) and treats a grant
 * whose units differ as BootstrapRequiredMessage{reason:
 * BootstrapPermissionChanged}: that message goes only to the subscriptions
 * that saw the change happen, so a client that missed it learns it from
 * the units of its next grant. The units are what the server compares
 * to send it (a change undone in between needs nothing: replays and live
 * changes are filtered by the current units).
 */
export interface GroupRequest {
  group: string;
  since?: number /* int64 */;
}
/**
 * HelloMessage opens a session. It must be the first message: anything
 * else first is answered by ErrorMessage{code: ErrorHelloRequired} and the
 * session is closed. Over the fallback transport, wait for the hello's
 * POST to complete before sending more.
 */
export interface HelloMessage {
  type: 'hello';
  /**
   * Token is an OAuth2 access token or a personal access token, validated
   * like an API v1 bearer token (never sent in the URL).
   */
  token: string;
  client_id?: string;
  /**
   * Protocol is the client's ProtocolVersion (informational).
   */
  protocol?: number /* int */;
  /**
   * BuildID is the build of the client app; when it differs from the
   * server's, the server sends NoticeMessage{kind: NoticeNewBuild}.
   */
  build_id?: string;
  /**
   * LastSyncID is the Since of every group that does not give one.
   */
  last_sync_id?: number /* int64 */;
  groups?: GroupRequest[];
}
/**
 * SubscribeMessage adds groups to the session (or restarts the replay of an
 * already subscribed group from a new Since). Answered by SubscribedMessage.
 */
export interface SubscribeMessage {
  type: 'subscribe';
  groups: GroupRequest[];
}
/**
 * UnsubscribeMessage removes groups from the session (no answer; deltas of
 * these groups already on their way may still arrive).
 */
export interface UnsubscribeMessage {
  type: 'unsubscribe';
  groups: string[];
}
/**
 * BarrierMessage asks the server to answer BarrierOKMessage once
 * everything committed to the sync log before the barrier arrived has been
 * sent for every subscribed group (all of them caught up).
 */
export interface BarrierMessage {
  type: 'barrier';
  id: string;
}
/**
 * PingMessage is answered by PongMessage (keep-alive; it also tells the
 * client the server's position).
 */
export interface PingMessage {
  type: 'ping';
  id?: string;
}
/**
 * Refusal is a requested group the session did not get. Reason is
 * RefusedForbidden (not readable — or not existing, or not a client group:
 * the answer never tells these apart) or RefusedLimit (the per-user
 * subscription limit is reached).
 */
export interface Refusal {
  group: string;
  reason: RefusalReason;
}
export const RefusedForbidden = "forbidden";
export const RefusedLimit = "limit";
/**
 * WelcomeMessage answers HelloMessage.
 */
export interface WelcomeMessage {
  type: 'welcome';
  /**
   * ServerSyncID is the server's position when the session started.
   */
  server_sync_id: number /* int64 */;
  viewer_id: number /* int64 */;
  /**
   * Granted are the requested groups the session subscribed, with the
   * viewer's units in them; Refused the others.
   */
  granted: Grant[];
  refused: Refusal[];
  /**
   * Grants are the viewer's implicit grants (as GET /-/sync/grants): the
   * groups to keep in the workspace. Others are granted on demand.
   */
  grants: Grant[];
  build_id: string;
  protocol: number /* int */;
  schemas: { [key: Model]: number /* int */};
  /**
   * Profile is the viewer's own User entity (a change with op U). It is
   * sent here, and later changes of it are sent to the viewer's sessions
   * whether or not they subscribed its group, because a viewer may not be
   * able to read the group that holds it (a restricted user with
   * visibility limited cannot read profiles:limited).
   */
  profile?: Change;
}
/**
 * SubscribedMessage answers SubscribeMessage.
 */
export interface SubscribedMessage {
  type: 'subscribed';
  granted: Grant[];
  refused: Refusal[];
}
/**
 * Change is one sync log entry as sent to clients.
 */
export interface Change {
  /**
   * V is the entry's sync id (the entity's version).
   */
  v: number /* int64 */;
  /**
   * G is the group the entry belongs to.
   */
  g: string;
  m: Model;
  /**
   * ID is the entity's id.
   */
  id: number /* int64 */;
  /**
   * Op is OpUpsert or OpDelete.
   */
  op: Op;
  /**
   * D is the entity (the model's DTO) for OpUpsert; absent for OpDelete.
   */
  d?: unknown;
}
/**
 * DeltaMessage carries changes, in sync id order per group. To is the
 * position up to which every caught-up group of the session is complete
 * with this frame (it may be below the changes' v).
 */
export interface DeltaMessage {
  type: 'delta';
  to: number /* int64 */;
  changes: Change[];
}
/**
 * CaughtUpMessage says that every subscribed group has been replayed and is
 * live, complete up to SyncID. Sent after the hello's and each subscribe's
 * replays finished; a client may then flush its offline queue.
 */
export interface CaughtUpMessage {
  type: 'caught_up';
  sync_id: number /* int64 */;
}
/**
 * BootstrapRequiredMessage says that the client cannot get a group's
 * missing changes from the stream: it must drop what it holds of the group
 * and load it again (B6's bootstrap). The subscription stays: changes keep
 * arriving, and the bootstrap's watermark makes the overlap harmless.
 */
export interface BootstrapRequiredMessage {
  type: 'bootstrap_required';
  group: string;
  reason: BootstrapReason;
  /**
   * Model is set when only the entities of this model are concerned
   * (a re-bootstrap marker in the sync log).
   */
  model?: Model;
}
/**
 * BootstrapCursorTrimmed: the group's position is older than the sync
 * log retention.
 */
export const BootstrapCursorTrimmed = "cursor_trimmed";
/**
 * BootstrapReplayTooLong: the group has more entries to replay than the
 * server's limit ([livesync] MAX_REPLAY): a bootstrap is cheaper.
 */
export const BootstrapReplayTooLong = "replay_too_long";
/**
 * BootstrapPermissionChanged: the viewer's units in the group changed;
 * what they may read of it is no longer what they hold. Not sent again
 * on resume: see GroupRequest.
 */
export const BootstrapPermissionChanged = "permission_changed";
/**
 * BootstrapCursorUnknown: the group's position is ahead of the sync
 * log (it comes from another database, e.g. before a restore).
 */
export const BootstrapCursorUnknown = "cursor_unknown";
/**
 * GroupRevokedMessage says that the viewer may no longer read a group: the
 * subscription is gone and the client must purge the group's entities.
 */
export interface GroupRevokedMessage {
  type: 'group_revoked';
  group: string;
}
/**
 * BarrierOKMessage answers BarrierMessage: every subscribed group is
 * complete up to SyncID.
 */
export interface BarrierOKMessage {
  type: 'barrier_ok';
  id: string;
  sync_id: number /* int64 */;
}
/**
 * SessionInvalidMessage says that the token is invalid, expired or revoked,
 * or that the account may no longer sign in; the server closes the session.
 * The client should get a new token (or sign in again) and reconnect.
 */
export interface SessionInvalidMessage {
  type: 'session_invalid';
  message: string;
}
/**
 * NoticeMessage informs the client about the server.
 */
export interface NoticeMessage {
  type: 'notice';
  kind: NoticeKind;
}
/**
 * NoticeNewBuild: the server runs another build than the client's
 * (HelloMessage.BuildID); the client should update itself.
 */
export const NoticeNewBuild = "new_build";
/**
 * NoticeShutdown: the server is shutting down; reconnect (with backoff).
 */
export const NoticeShutdown = "shutdown";
/**
 * PongMessage answers PingMessage. SyncID is the server's position: every
 * caught-up group is complete up to it.
 */
export interface PongMessage {
  type: 'pong';
  id?: string;
  sync_id: number /* int64 */;
}
/**
 * GrantsMessage tells the client that the viewer's implicit grants
 * (WelcomeMessage.Grants) changed, e.g. after they were made a
 * collaborator: the workspace may subscribe the new groups. Groups that
 * are no longer readable are revoked separately (GroupRevokedMessage).
 */
export interface GrantsMessage {
  type: 'grants';
  grants: Grant[];
}
/**
 * ResumeFromCursorMessage says that the client does not read fast enough:
 * the server dropped what it had not sent yet and closes the session. Every
 * caught-up group is complete up to SyncID; the client reconnects and
 * resumes each group from its position.
 */
export interface ResumeFromCursorMessage {
  type: 'resume_from_cursor';
  sync_id: number /* int64 */;
}
/**
 * ErrorMessage reports a message the server could not handle (the session
 * goes on unless the server closes it).
 */
export interface ErrorMessage {
  type: 'error';
  code: ErrorCode;
  message: string;
}
export const ErrorBadMessage = "bad_message";
export const ErrorHelloRequired = "hello_required";
export const ErrorTooManyBarriers = "too_many_barriers";
export const ErrorTooManyConnections = "too_many_connections";
export const ErrorInternal = "internal";
/**
 * SessionMessage is the first event of the fallback transport (GET
 * /-/sync/sse): POST client messages to /-/sync/send with the header
 * X-Livesync-Session set to Session.
 */
export interface SessionMessage {
  type: 'session';
  session: string;
}
/**
 * SessionHeader is the request header of POST /-/sync/send naming the
 * fallback session.
 */
export const SessionHeader = "X-Livesync-Session";

//////////
// source: protocol.go
/*
Package protocol defines livesync's wire types (PLAN §4.4, §4.6): the
normalized, viewer-independent entity DTOs the materializer writes to the
sync log, the sync group names and the units that gate repository-scoped
entities. The TypeScript client's types are generated from this package
(next/tools/gen-protocol.sh → next/src/protocol/types.gen.ts); keep it free
of anything tygo cannot translate (functions are ignored by tygo, so only
put small, pure helpers here).

Conventions: JSON field names follow API v1 (snake_case, the same name as
the corresponding API v1 field where one exists); references to other
entities are ids (normalized, never embedded objects); times are RFC 3339
strings in UTC; optional times are omitted when unset.
*/

/**
 * Model names an entity type. It is written to livesync_log.model and is
 * the "m" of a delta change.
 */
export type Model = string;
export const ModelRepository: Model = "Repository";
export const ModelUser: Model = "User";
export const ModelOrgUser: Model = "OrgUser";
export const ModelTeam: Model = "Team";
export const ModelTeamUser: Model = "TeamUser";
export const ModelTeamRepo: Model = "TeamRepo";
export const ModelTeamUnit: Model = "TeamUnit";
export const ModelCollaboration: Model = "Collaboration";
export const ModelAccess: Model = "Access";
export const ModelRepoUnit: Model = "RepoUnit";
export const ModelLabel: Model = "Label";
export const ModelMilestone: Model = "Milestone";
export const ModelProject: Model = "Project";
export const ModelProjectColumn: Model = "ProjectColumn";
export const ModelProjectIssue: Model = "ProjectIssue";
export const ModelIssue: Model = "Issue";
export const ModelIssueBody: Model = "IssueBody";
export const ModelIssueLabel: Model = "IssueLabel";
export const ModelIssueAssignee: Model = "IssueAssignee";
export const ModelPullRequest: Model = "PullRequest";
export const ModelAutoMerge: Model = "AutoMerge";
export const ModelBranch: Model = "Branch";
export const ModelRelease: Model = "Release";
export const ModelCommitStatus: Model = "CommitStatus";
export const ModelActionRun: Model = "ActionRun";
export const ModelActionRunJob: Model = "ActionRunJob";
export const ModelNotification: Model = "Notification";
export const ModelStopwatch: Model = "Stopwatch";
export const ModelIssueWatch: Model = "IssueWatch";
export const ModelWatch: Model = "Watch";
export const ModelStar: Model = "Star";
export const ModelBlockedUser: Model = "BlockedUser";
export const ModelComment: Model = "Comment";
export const ModelReaction: Model = "Reaction";
export const ModelReview: Model = "Review";
export const ModelReviewState: Model = "ReviewState";
export const ModelAttachment: Model = "Attachment";
export const ModelIssueDependency: Model = "IssueDependency";
export const ModelTrackedTime: Model = "TrackedTime";
export const ModelContentHistory: Model = "ContentHistory";
export const SchemaRepository = 1;
export const SchemaUser = 1;
export const SchemaOrgUser = 1;
export const SchemaTeam = 1;
export const SchemaTeamUser = 1;
export const SchemaTeamRepo = 1;
export const SchemaTeamUnit = 1;
export const SchemaCollaboration = 1;
export const SchemaAccess = 1;
export const SchemaRepoUnit = 1;
export const SchemaLabel = 1;
export const SchemaMilestone = 1;
export const SchemaProject = 1;
export const SchemaProjectColumn = 1;
export const SchemaProjectIssue = 1;
export const SchemaIssue = 1;
export const SchemaIssueBody = 1;
export const SchemaIssueLabel = 1;
export const SchemaIssueAssignee = 1;
export const SchemaPullRequest = 1;
export const SchemaAutoMerge = 1;
export const SchemaBranch = 1;
export const SchemaRelease = 1;
export const SchemaCommitStatus = 1;
export const SchemaActionRun = 1;
export const SchemaActionRunJob = 1;
export const SchemaNotification = 1;
export const SchemaStopwatch = 1;
export const SchemaIssueWatch = 1;
export const SchemaWatch = 1;
export const SchemaStar = 1;
export const SchemaBlockedUser = 1;
export const SchemaComment = 1;
export const SchemaReaction = 1;
export const SchemaReview = 1;
export const SchemaReviewState = 1;
export const SchemaAttachment = 1;
export const SchemaIssueDependency = 1;
export const SchemaTrackedTime = 1;
export const SchemaContentHistory = 1;
/**
 * Op is the operation of a sync log entry (livesync_log.op, the "op" of a
 * delta change).
 */
export type Op = string;
/**
 * OpUpsert: the payload is the entity's full current state. Applying it
 * is idempotent (clients keep it only if its sync id is newer).
 */
export const OpUpsert: Op = "U";
/**
 * OpDelete: the entity is gone from the group (deleted, or moved to
 * another group, which gets an OpUpsert). No payload.
 */
export const OpDelete: Op = "D";
/**
 * OpRebootstrap: changes to the model may have been lost (a capture
 * trigger was missing or stale, see RebootstrapMarker). Clients holding
 * entities of the model must re-bootstrap the groups they hold. Written
 * to GroupAll with entity id 0.
 */
export const OpRebootstrap: Op = "B";
/**
 * OpPermission: who may read what may have changed (a permission
 * epoch, PLAN §4.5). Written to GroupPermission with entity id 0 and a
 * PermissionChange payload, before the entries of the same transaction.
 * Never sent to clients: the hub recomputes the grants of the affected
 * viewers and re-checks the affected groups' subscribers.
 */
export const OpPermission: Op = "P";
/**
 * RebootstrapMarker is the payload of an OpRebootstrap entry.
 */
export interface RebootstrapMarker {
  /**
   * Table whose entities must be re-bootstrapped.
   */
  table: string;
  /**
   * Epoch is the table's schema epoch after the repair.
   */
  epoch: number /* int64 */;
  /**
   * Reason says why: RebootstrapTriggerRepaired (changes may have been
   * lost) or RebootstrapPlacementChanged (a new livesync version places
   * the table's entities in other groups or units).
   */
  reason: string;
}
export const RebootstrapTriggerRepaired = "trigger_repaired";
export const RebootstrapPlacementChanged = "placement_changed";
/**
 * PermissionChange is the payload of an OpPermission entry: the subjects
 * whose access may have changed. The hub recomputes the grants of Users,
 * re-checks the subscribers of the repo:{id} groups of Repos (and of the
 * issue:{id} groups of those repositories), and the subscribers of the
 * org:{id} and profile:{id} groups of Owners (a user or organization whose
 * visibility, or whose set of possible viewers, changed). All means
 * everything may have changed (writes to a permission table may have been
 * lost): recompute every grant and re-check every subscription.
 * Touched are the rows of the busy permission tables (repository, user)
 * that were updated without a visible change of their permission state —
 * mostly counters and timestamps (an issue created, a sign-in), but the
 * updates may also have changed the state and changed it back before the
 * materializer read the row (a repository made public and private again).
 * A grant or decision computed in between saw another state: the hub
 * re-checks only the subscriptions whose decision recorded another state
 * of a touched row (perm.Basis.Stale), the grant caches drop only such
 * entries, so a counter update costs no recomputation.
 */
export interface PermissionChange {
  users?: number /* int64 */[];
  repos?: number /* int64 */[];
  owners?: number /* int64 */[];
  all?: boolean;
  touched?: PermissionTouch[];
}
/**
 * PermissionTouch is a row of a busy permission table that was updated
 * without a visible change of its permission state (PermissionChange.Touched).
 */
export interface PermissionTouch {
  /**
   * Kind is the row's table: TouchRepository or TouchUser.
   */
  kind: string;
  id: number /* int64 */;
  /**
   * State is the fingerprint of the row's permission state after the
   * updates (perm.RepositoryState, perm.UserState).
   */
  state: string;
}
export const TouchRepository = "repository";
export const TouchUser = "user";
export const GroupPrefixUser = "user";
export const GroupPrefixOrg = "org";
export const GroupPrefixRepo = "repo";
export const GroupPrefixIssue = "issue";
export const GroupPrefixProfile = "profile";
export const GroupPrefixProfiles = "profiles";
export const GroupProfilesPublic = GroupPrefixProfiles + ":public";
export const GroupProfilesLimited = GroupPrefixProfiles + ":limited";
/**
 * GroupAll is the pseudo group of the entries that concern every client: the
 * schema epoch markers (OpRebootstrap), which carry no entity data. Readers
 * of a group always receive GroupAll entries too. Nothing else is written to
 * it (PLAN §4.5: nothing is broadcast instance-wide).
 */
export const GroupAll = "*";
/**
 * GroupPermission is the pseudo group of the permission epochs
 * (OpPermission). No client is ever granted it and no group's readers
 * receive it; the hub reads it from the tailer.
 */
export const GroupPermission = "!perm";
/**
 * Unit is what a reader of a group needs (livesync_log.unit) to receive an
 * entity of it. In repo:{id} and issue:{id} groups it is a repository unit,
 * checked with Permission.CanRead(unit) (PLAN §4.4); several alternatives are
 * separated by "|" (the entity is visible with any of them), and the same
 * names identify unit types in RepoUnit/TeamUnit. In user:{id} groups it is
 * UnitSelf (that user only; nobody else is granted the group anyway); in
 * org:{id} groups UnitNone (anyone who may see the organization) or
 * UnitMembers (its members only); in the profile groups UnitNone. UnitNone
 * means any read access to the group.
 */
export type Unit = string;
export const UnitNone: Unit = "";
export const UnitCode: Unit = "code";
export const UnitIssues: Unit = "issues";
export const UnitPulls: Unit = "pulls";
export const UnitIssuesOrPulls: Unit = "issues|pulls";
export const UnitReleases: Unit = "releases";
export const UnitWiki: Unit = "wiki";
export const UnitExternalWiki: Unit = "ext_wiki";
export const UnitExternalTracker: Unit = "ext_issues";
export const UnitProjects: Unit = "projects";
export const UnitPackages: Unit = "packages";
export const UnitActions: Unit = "actions";
/**
 * UnitSelf: in user:{id}, only that user.
 */
export const UnitSelf: Unit = "self";
/**
 * UnitMembers: in org:{id}, only the organization's members.
 */
export const UnitMembers: Unit = "members";
/**
 * Grant is a group a viewer may read and the units they may read in it
 * (UnitNone entries of the group are readable whenever it is granted).
 */
export interface Grant {
  group: string;
  units: Unit[];
}
/**
 * Grants is the answer of GET /-/sync/grants: the groups granted to the
 * viewer without asking (their own user group and profile group, the
 * profile directories, the organizations they are a member of and the
 * repositories they own or were given access to). Other groups (public
 * repositories and organizations, other users' profiles, issues) are
 * checked on demand (GET /-/sync/grants?group=…, which answers one Grant).
 * Site administrators get no implicit groups.
 */
export interface Grants {
  viewer_id: number /* int64 */;
  grants: Grant[];
}
