// Code generated by tygo. DO NOT EDIT.
// Copyright 2026 The Forgejo Authors. All rights reserved.
// SPDX-License-Identifier: GPL-3.0-or-later
//
// Generated by next/tools/gen-protocol.sh from services/livesync/protocol:
// change the Go types and re-run the script (--check verifies it in CI).

//////////
// source: entities.go

/**
 * Repository is a repository (group repo:{id}, unit none).
 */
export interface Repository {
  id: number /* int64 */;
  owner_id: number /* int64 */;
  owner_name: string;
  name: string;
  full_name: string;
  description: string;
  website: string;
  private: boolean;
  fork: boolean;
  parent_id: number /* int64 */;
  template: boolean;
  mirror: boolean;
  archived: boolean;
  empty: boolean;
  default_branch: string;
  stars_count: number /* int */;
  forks_count: number /* int */;
  watchers_count: number /* int */;
  topics: string[];
  object_format_name: string;
  avatar_url: string;
  created_at: string /* RFC 3339, UTC */;
  updated_at: string /* RFC 3339, UTC */;
  archived_at?: string /* RFC 3339, UTC */;
}
/**
 * User is the public profile of a user or organization (group user:{id}, or
 * org:{id} for an organization). Email addresses, admin/active/restricted
 * flags and settings are never included.
 */
export interface User {
  id: number /* int64 */;
  login: string;
  full_name: string;
  avatar_url: string;
  type: string; // "user", "organization", "bot", "remote", "reserved"
  visibility: string; // "public", "limited", "private"
  description: string;
  website: string;
  location: string;
  /**
   * Pronouns is empty when the user keeps them private.
   */
  pronouns: string;
  created_at: string /* RFC 3339, UTC */;
}
/**
 * OrgUser is an organization membership (group org:{org_id}).
 */
export interface OrgUser {
  id: number /* int64 */;
  org_id: number /* int64 */;
  user_id: number /* int64 */;
  public: boolean;
}
/**
 * Team is an organization team (group org:{org_id}).
 */
export interface Team {
  id: number /* int64 */;
  org_id: number /* int64 */;
  name: string;
  description: string;
  permission: string; // "none", "read", "write", "admin", "owner"
  includes_all_repositories: boolean;
  can_create_org_repo: boolean;
  num_members: number /* int */;
  num_repos: number /* int */;
}
/**
 * TeamUser is a team membership (group org:{org_id}).
 */
export interface TeamUser {
  id: number /* int64 */;
  org_id: number /* int64 */;
  team_id: number /* int64 */;
  user_id: number /* int64 */;
}
/**
 * TeamRepo gives a team access to a repository (group org:{org_id}).
 */
export interface TeamRepo {
  id: number /* int64 */;
  org_id: number /* int64 */;
  team_id: number /* int64 */;
  repo_id: number /* int64 */;
}
/**
 * TeamUnit is a team's access mode for one unit type (group org:{org_id}).
 */
export interface TeamUnit {
  id: number /* int64 */;
  org_id: number /* int64 */;
  team_id: number /* int64 */;
  type: Unit;
  permission: string;
}
/**
 * Collaboration makes a user a collaborator of a repository (group
 * repo:{repo_id}).
 */
export interface Collaboration {
  id: number /* int64 */;
  repo_id: number /* int64 */;
  user_id: number /* int64 */;
  permission: string;
  created_at: string /* RFC 3339, UTC */;
  updated_at: string /* RFC 3339, UTC */;
}
/**
 * Access is a user's computed access mode to a repository (group
 * user:{user_id}).
 */
export interface Access {
  id: number /* int64 */;
  user_id: number /* int64 */;
  repo_id: number /* int64 */;
  permission: string;
}
/**
 * RepoUnit is an enabled unit of a repository with its configuration
 * (group repo:{repo_id}).
 */
export interface RepoUnit {
  id: number /* int64 */;
  repo_id: number /* int64 */;
  type: Unit;
  config: { [key: string]: any};
  /**
   * DefaultPermissions: "", "read" or "write" (for everyone signed in).
   */
  default_permissions: string;
  created_at: string /* RFC 3339, UTC */;
}
/**
 * Label is a repository label (group repo:{repo_id}, unit issues|pulls) or
 * an organization label (group org:{org_id}).
 */
export interface Label {
  id: number /* int64 */;
  repo_id: number /* int64 */;
  org_id: number /* int64 */;
  name: string;
  exclusive: boolean;
  description: string;
  color: string;
  num_issues: number /* int */;
  num_closed_issues: number /* int */;
  created_at: string /* RFC 3339, UTC */;
  updated_at: string /* RFC 3339, UTC */;
  archived_at?: string /* RFC 3339, UTC */;
}
/**
 * Milestone is a repository milestone (group repo:{repo_id}, unit
 * issues|pulls).
 */
export interface Milestone {
  id: number /* int64 */;
  repo_id: number /* int64 */;
  title: string;
  description: string;
  state: string; // "open", "closed"
  open_issues: number /* int */;
  closed_issues: number /* int */;
  due_on?: string /* RFC 3339, UTC */;
  closed_at?: string /* RFC 3339, UTC */;
  created_at: string /* RFC 3339, UTC */;
  updated_at: string /* RFC 3339, UTC */;
}
/**
 * Project is a project board of a repository (group repo:{repo_id}, unit
 * projects) or of a user/organization (group user:/org:{owner_id}).
 */
export interface Project {
  id: number /* int64 */;
  title: string;
  description: string;
  owner_id: number /* int64 */;
  repo_id: number /* int64 */;
  creator_id: number /* int64 */;
  closed: boolean;
  template_type: number /* int */;
  card_type: number /* int */;
  type: number /* int */; // 1 individual, 2 repository, 3 organization
  created_at: string /* RFC 3339, UTC */;
  updated_at: string /* RFC 3339, UTC */;
  closed_at?: string /* RFC 3339, UTC */;
}
/**
 * ProjectColumn is a column of a project board (the project's group).
 */
export interface ProjectColumn {
  id: number /* int64 */;
  project_id: number /* int64 */;
  title: string;
  default: boolean;
  sorting: number /* int */;
  color: string;
  creator_id: number /* int64 */;
  created_at: string /* RFC 3339, UTC */;
  updated_at: string /* RFC 3339, UTC */;
}
/**
 * ProjectIssue places an issue on a project board (the project's group).
 */
export interface ProjectIssue {
  id: number /* int64 */;
  issue_id: number /* int64 */;
  project_id: number /* int64 */;
  column_id: number /* int64 */;
  sorting: number /* int64 */;
}
/**
 * Issue is the summary of an issue or pull request (group repo:{repo_id},
 * unit issues or pulls). Its body is the IssueBody entity of issue:{id}.
 */
export interface Issue {
  id: number /* int64 */;
  repo_id: number /* int64 */;
  number: number /* int64 */;
  poster_id: number /* int64 */;
  original_author: string;
  original_author_id: number /* int64 */;
  title: string;
  content_version: number /* int */;
  milestone_id: number /* int64 */;
  priority: number /* int */;
  state: string; // "open", "closed"
  is_pull: boolean;
  comments: number /* int */;
  ref: string;
  pin_order: number /* int */;
  is_locked: boolean;
  due_date?: string /* RFC 3339, UTC */;
  created_at: string /* RFC 3339, UTC */;
  updated_at: string /* RFC 3339, UTC */;
  closed_at?: string /* RFC 3339, UTC */;
}
/**
 * IssueBody is the description of an issue or pull request (group
 * issue:{id}, same id as the Issue).
 */
export interface IssueBody {
  id: number /* int64 */;
  repo_id: number /* int64 */;
  body: string;
  body_html: string;
  content_version: number /* int */;
}
/**
 * IssueLabel puts a label on an issue (the issue's repo:{repo_id} group).
 */
export interface IssueLabel {
  id: number /* int64 */;
  issue_id: number /* int64 */;
  label_id: number /* int64 */;
}
/**
 * IssueAssignee assigns a user to an issue (the issue's repo:{repo_id}
 * group).
 */
export interface IssueAssignee {
  id: number /* int64 */;
  issue_id: number /* int64 */;
  assignee_id: number /* int64 */;
}
/**
 * PullRequest is the pull-request part of an issue (group
 * repo:{base_repo_id}, unit pulls).
 */
export interface PullRequest {
  id: number /* int64 */;
  issue_id: number /* int64 */;
  number: number /* int64 */;
  status: string; // "conflict", "checking", "mergeable", "manually_merged", "error", "empty", "ancestor"
  head_repo_id: number /* int64 */;
  base_repo_id: number /* int64 */;
  head_branch: string;
  base_branch: string;
  merge_base: string;
  allow_maintainer_edit: boolean;
  merged: boolean;
  merge_commit_sha: string;
  merger_id: number /* int64 */;
  merged_at?: string /* RFC 3339, UTC */;
  commits_ahead: number /* int */;
  commits_behind: number /* int */;
  conflicted_files: string[];
  flow: number /* int */; // 0 branches, 1 AGit
}
/**
 * AutoMerge schedules a pull request to be merged when its checks pass (the
 * pull request's group, unit pulls).
 */
export interface AutoMerge {
  id: number /* int64 */;
  pull_id: number /* int64 */;
  doer_id: number /* int64 */;
  merge_style: string;
  delete_branch_after_merge: boolean;
  created_at: string /* RFC 3339, UTC */;
}
/**
 * Branch is a branch and its head commit (group repo:{repo_id}, unit code).
 */
export interface Branch {
  id: number /* int64 */;
  repo_id: number /* int64 */;
  name: string;
  commit_id: string;
  commit_message: string;
  commit_time: string /* RFC 3339, UTC */;
  pusher_id: number /* int64 */;
  is_deleted: boolean;
  deleted_by_id: number /* int64 */;
  deleted_at?: string /* RFC 3339, UTC */;
  created_at: string /* RFC 3339, UTC */;
  updated_at: string /* RFC 3339, UTC */;
}
/**
 * Release is a release or tag (group repo:{repo_id}, unit releases).
 */
export interface Release {
  id: number /* int64 */;
  repo_id: number /* int64 */;
  publisher_id: number /* int64 */;
  tag_name: string;
  target_commitish: string;
  name: string;
  sha: string;
  body: string;
  body_html: string;
  draft: boolean;
  prerelease: boolean;
  is_tag: boolean;
  num_commits: number /* int64 */;
  hide_archive_links: boolean;
  original_author: string;
  created_at: string /* RFC 3339, UTC */;
}
/**
 * CommitStatus is one status reported for a commit (group repo:{repo_id},
 * unit code).
 */
export interface CommitStatus {
  id: number /* int64 */;
  repo_id: number /* int64 */;
  index: number /* int64 */;
  state: string; // "pending", "success", "error", "failure", "warning"
  sha: string;
  target_url: string;
  description: string;
  context: string;
  creator_id: number /* int64 */;
  created_at: string /* RFC 3339, UTC */;
  updated_at: string /* RFC 3339, UTC */;
}
/**
 * ActionRun is a workflow run (group repo:{repo_id}, unit actions).
 */
export interface ActionRun {
  id: number /* int64 */;
  repo_id: number /* int64 */;
  owner_id: number /* int64 */;
  title: string;
  workflow_id: string;
  run_number: number /* int64 */;
  trigger_user_id: number /* int64 */;
  ref: string;
  commit_sha: string;
  event: string;
  trigger_event: string;
  status: string;
  is_fork_pull_request: boolean;
  pull_request_id: number /* int64 */;
  need_approval: boolean;
  approved_by: number /* int64 */;
  started?: string /* RFC 3339, UTC */;
  stopped?: string /* RFC 3339, UTC */;
  created_at: string /* RFC 3339, UTC */;
  updated_at: string /* RFC 3339, UTC */;
}
/**
 * ActionRunJob is a job of a workflow run (group repo:{repo_id}, unit
 * actions).
 */
export interface ActionRunJob {
  id: number /* int64 */;
  run_id: number /* int64 */;
  repo_id: number /* int64 */;
  owner_id: number /* int64 */;
  commit_sha: string;
  name: string;
  attempt: number /* int64 */;
  job_id: string;
  needs: string[];
  runs_on: string[];
  task_id: number /* int64 */;
  status: string;
  started?: string /* RFC 3339, UTC */;
  stopped?: string /* RFC 3339, UTC */;
  created_at: string /* RFC 3339, UTC */;
  updated_at: string /* RFC 3339, UTC */;
}
/**
 * Notification is an inbox entry of a user (group user:{user_id}).
 */
export interface Notification {
  id: number /* int64 */;
  user_id: number /* int64 */;
  repo_id: number /* int64 */;
  status: string; // "unread", "read", "pinned"
  subject: string; // "issue", "pull", "commit", "repository"
  issue_id: number /* int64 */;
  comment_id: number /* int64 */;
  created_at: string /* RFC 3339, UTC */;
  updated_at: string /* RFC 3339, UTC */;
}
/**
 * Stopwatch is a user's running time tracker on an issue (group
 * user:{user_id}).
 */
export interface Stopwatch {
  id: number /* int64 */;
  user_id: number /* int64 */;
  issue_id: number /* int64 */;
  created_at: string /* RFC 3339, UTC */;
}
/**
 * IssueWatch is a user's explicit (un)subscription to an issue (group
 * user:{user_id}).
 */
export interface IssueWatch {
  id: number /* int64 */;
  user_id: number /* int64 */;
  issue_id: number /* int64 */;
  is_watching: boolean;
  created_at: string /* RFC 3339, UTC */;
  updated_at: string /* RFC 3339, UTC */;
}
/**
 * Watch is a user's watch settings for a repository (group user:{user_id}).
 */
export interface Watch {
  id: number /* int64 */;
  user_id: number /* int64 */;
  repo_id: number /* int64 */;
  automatic: boolean;
  issues: boolean;
  pull_requests: boolean;
  releases: boolean;
  created_at: string /* RFC 3339, UTC */;
  updated_at: string /* RFC 3339, UTC */;
}
/**
 * Star is a user's star on a repository (group user:{user_id}).
 */
export interface Star {
  id: number /* int64 */;
  user_id: number /* int64 */;
  repo_id: number /* int64 */;
  created_at: string /* RFC 3339, UTC */;
}
/**
 * BlockedUser records that user_id blocked block_id (group user:{user_id}).
 */
export interface BlockedUser {
  id: number /* int64 */;
  user_id: number /* int64 */;
  block_id: number /* int64 */;
  created_at: string /* RFC 3339, UTC */;
}
/**
 * Comment is one timeline entry of an issue or pull request: a comment, a
 * code review comment or an event (group issue:{issue_id}, unit issues or
 * pulls). Type is Forgejo's comment type name ("comment", "close", "label",
 * "code", ...); the other fields are set as the type uses them.
 */
export interface Comment {
  id: number /* int64 */;
  issue_id: number /* int64 */;
  type: string;
  poster_id: number /* int64 */;
  original_author: string;
  original_author_id: number /* int64 */;
  body: string;
  body_html: string;
  content_version: number /* int */;
  label_id: number /* int64 */;
  old_project_id: number /* int64 */;
  project_id: number /* int64 */;
  old_milestone_id: number /* int64 */;
  milestone_id: number /* int64 */;
  time_id: number /* int64 */;
  assignee_id: number /* int64 */;
  assignee_team_id: number /* int64 */;
  removed_assignee: boolean;
  resolve_doer_id: number /* int64 */;
  old_title: string;
  new_title: string;
  old_ref: string;
  new_ref: string;
  dependent_issue_id: number /* int64 */;
  line: number /* int64 */;
  extra_lines_count: number /* int64 */;
  path: string;
  diff_hunk: string;
  commit_id: string;
  review_id: number /* int64 */;
  invalidated: boolean;
  ref_repo_id: number /* int64 */;
  ref_issue_id: number /* int64 */;
  ref_comment_id: number /* int64 */;
  ref_action: number /* int */;
  ref_is_pull: boolean;
  created_at: string /* RFC 3339, UTC */;
  updated_at: string /* RFC 3339, UTC */;
}
/**
 * Reaction is an emoji reaction on an issue or comment (group
 * issue:{issue_id}).
 */
export interface Reaction {
  id: number /* int64 */;
  issue_id: number /* int64 */;
  comment_id: number /* int64 */;
  user_id: number /* int64 */;
  original_author: string;
  content: string;
  created_at: string /* RFC 3339, UTC */;
}
/**
 * Review is a pull request review or review request (group
 * issue:{issue_id}, unit pulls).
 */
export interface Review {
  id: number /* int64 */;
  issue_id: number /* int64 */;
  state: string; // "PENDING", "APPROVED", "COMMENT", "REQUEST_CHANGES", "REQUEST_REVIEW"
  reviewer_id: number /* int64 */;
  reviewer_team_id: number /* int64 */;
  original_author: string;
  body: string;
  body_html: string;
  official: boolean;
  commit_id: string;
  stale: boolean;
  dismissed: boolean;
  created_at: string /* RFC 3339, UTC */;
  updated_at: string /* RFC 3339, UTC */;
}
/**
 * ReviewState holds a user's "viewed files" of a pull request at a commit
 * (group user:{user_id}). Values: 0 unviewed, 1 changed since viewed,
 * 2 viewed.
 */
export interface ReviewState {
  id: number /* int64 */;
  user_id: number /* int64 */;
  pull_id: number /* int64 */;
  commit_sha: string;
  updated_files: { [key: string]: number /* uint8 */};
  updated_at: string /* RFC 3339, UTC */;
}
/**
 * Attachment is a file attached to an issue/comment (group
 * issue:{issue_id}) or to a release (group repo:{repo_id}, unit releases).
 */
export interface Attachment {
  id: number /* int64 */;
  uuid: string;
  uploader_id: number /* int64 */;
  repo_id: number /* int64 */;
  issue_id: number /* int64 */;
  release_id: number /* int64 */;
  comment_id: number /* int64 */;
  name: string;
  size: number /* int64 */;
  download_count: number /* int64 */;
  external_url: string;
  created_at: string /* RFC 3339, UTC */;
}
/**
 * IssueDependency says issue_id is blocked by dependency_id (group
 * issue:{issue_id}).
 */
export interface IssueDependency {
  id: number /* int64 */;
  user_id: number /* int64 */;
  issue_id: number /* int64 */;
  dependency_id: number /* int64 */;
  created_at: string /* RFC 3339, UTC */;
  updated_at: string /* RFC 3339, UTC */;
}
/**
 * TrackedTime is time a user logged on an issue (group issue:{issue_id}).
 */
export interface TrackedTime {
  id: number /* int64 */;
  issue_id: number /* int64 */;
  user_id: number /* int64 */;
  time: number /* int64 */; // seconds
  deleted: boolean;
  created: string /* RFC 3339, UTC */;
}
/**
 * ContentHistory is one revision of an issue or comment body (group
 * issue:{issue_id}; fetched on demand only).
 */
export interface ContentHistory {
  id: number /* int64 */;
  poster_id: number /* int64 */;
  issue_id: number /* int64 */;
  comment_id: number /* int64 */;
  edited_at: string /* RFC 3339, UTC */;
  content_text: string;
  is_first_created: boolean;
  is_deleted: boolean;
}

//////////
// source: protocol.go
/*
Package protocol defines livesync's wire types (PLAN §4.4, §4.6): the
normalized, viewer-independent entity DTOs the materializer writes to the
sync log, the sync group names and the units that gate repository-scoped
entities. The TypeScript client's types are generated from this package
(next/tools/gen-protocol.sh → next/src/protocol/types.gen.ts); keep it free
of anything tygo cannot translate (functions are ignored by tygo, so only
put small, pure helpers here).

Conventions: JSON field names follow API v1 (snake_case, the same name as
the corresponding API v1 field where one exists); references to other
entities are ids (normalized, never embedded objects); times are RFC 3339
strings in UTC; optional times are omitted when unset.
*/

/**
 * Model names an entity type. It is written to livesync_log.model and is
 * the "m" of a delta change.
 */
export type Model = string;
export const ModelRepository: Model = "Repository";
export const ModelUser: Model = "User";
export const ModelOrgUser: Model = "OrgUser";
export const ModelTeam: Model = "Team";
export const ModelTeamUser: Model = "TeamUser";
export const ModelTeamRepo: Model = "TeamRepo";
export const ModelTeamUnit: Model = "TeamUnit";
export const ModelCollaboration: Model = "Collaboration";
export const ModelAccess: Model = "Access";
export const ModelRepoUnit: Model = "RepoUnit";
export const ModelLabel: Model = "Label";
export const ModelMilestone: Model = "Milestone";
export const ModelProject: Model = "Project";
export const ModelProjectColumn: Model = "ProjectColumn";
export const ModelProjectIssue: Model = "ProjectIssue";
export const ModelIssue: Model = "Issue";
export const ModelIssueBody: Model = "IssueBody";
export const ModelIssueLabel: Model = "IssueLabel";
export const ModelIssueAssignee: Model = "IssueAssignee";
export const ModelPullRequest: Model = "PullRequest";
export const ModelAutoMerge: Model = "AutoMerge";
export const ModelBranch: Model = "Branch";
export const ModelRelease: Model = "Release";
export const ModelCommitStatus: Model = "CommitStatus";
export const ModelActionRun: Model = "ActionRun";
export const ModelActionRunJob: Model = "ActionRunJob";
export const ModelNotification: Model = "Notification";
export const ModelStopwatch: Model = "Stopwatch";
export const ModelIssueWatch: Model = "IssueWatch";
export const ModelWatch: Model = "Watch";
export const ModelStar: Model = "Star";
export const ModelBlockedUser: Model = "BlockedUser";
export const ModelComment: Model = "Comment";
export const ModelReaction: Model = "Reaction";
export const ModelReview: Model = "Review";
export const ModelReviewState: Model = "ReviewState";
export const ModelAttachment: Model = "Attachment";
export const ModelIssueDependency: Model = "IssueDependency";
export const ModelTrackedTime: Model = "TrackedTime";
export const ModelContentHistory: Model = "ContentHistory";
export const SchemaRepository = 1;
export const SchemaUser = 1;
export const SchemaOrgUser = 1;
export const SchemaTeam = 1;
export const SchemaTeamUser = 1;
export const SchemaTeamRepo = 1;
export const SchemaTeamUnit = 1;
export const SchemaCollaboration = 1;
export const SchemaAccess = 1;
export const SchemaRepoUnit = 1;
export const SchemaLabel = 1;
export const SchemaMilestone = 1;
export const SchemaProject = 1;
export const SchemaProjectColumn = 1;
export const SchemaProjectIssue = 1;
export const SchemaIssue = 1;
export const SchemaIssueBody = 1;
export const SchemaIssueLabel = 1;
export const SchemaIssueAssignee = 1;
export const SchemaPullRequest = 1;
export const SchemaAutoMerge = 1;
export const SchemaBranch = 1;
export const SchemaRelease = 1;
export const SchemaCommitStatus = 1;
export const SchemaActionRun = 1;
export const SchemaActionRunJob = 1;
export const SchemaNotification = 1;
export const SchemaStopwatch = 1;
export const SchemaIssueWatch = 1;
export const SchemaWatch = 1;
export const SchemaStar = 1;
export const SchemaBlockedUser = 1;
export const SchemaComment = 1;
export const SchemaReaction = 1;
export const SchemaReview = 1;
export const SchemaReviewState = 1;
export const SchemaAttachment = 1;
export const SchemaIssueDependency = 1;
export const SchemaTrackedTime = 1;
export const SchemaContentHistory = 1;
/**
 * Op is the operation of a sync log entry (livesync_log.op, the "op" of a
 * delta change).
 */
export type Op = string;
/**
 * OpUpsert: the payload is the entity's full current state. Applying it
 * is idempotent (clients keep it only if its sync id is newer).
 */
export const OpUpsert: Op = "U";
/**
 * OpDelete: the entity is gone from the group (deleted, or moved to
 * another group, which gets an OpUpsert). No payload.
 */
export const OpDelete: Op = "D";
/**
 * OpRebootstrap: changes to the model may have been lost (a capture
 * trigger was missing or stale, see RebootstrapMarker). Clients holding
 * entities of the model must re-bootstrap the groups they hold. Written
 * to GroupAll with entity id 0.
 */
export const OpRebootstrap: Op = "B";
/**
 * RebootstrapMarker is the payload of an OpRebootstrap entry.
 */
export interface RebootstrapMarker {
  /**
   * Table whose capture trigger was (re)installed.
   */
  table: string;
  /**
   * Epoch is the table's schema epoch after the repair.
   */
  epoch: number /* int64 */;
}
export const GroupPrefixUser = "user";
export const GroupPrefixOrg = "org";
export const GroupPrefixRepo = "repo";
export const GroupPrefixIssue = "issue";
/**
 * GroupAll is the pseudo group of entries that concern every client: schema
 * epoch markers (OpRebootstrap) and deletes whose group is unknown (rows that
 * were never materialized while the entity index was still being backfilled).
 * Readers of a group always receive GroupAll entries too.
 */
export const GroupAll = "*";
/**
 * Unit is the repository unit a reader needs (livesync_log.unit) to receive
 * an entity of a repo:{id} or issue:{id} group, checked with
 * Permission.CanRead(unit) (PLAN §4.4). UnitNone means any read access to
 * the group. Several alternatives are separated by "|": the entity is visible
 * with any of them. The same names identify unit types in RepoUnit/TeamUnit.
 */
export type Unit = string;
export const UnitNone: Unit = "";
export const UnitCode: Unit = "code";
export const UnitIssues: Unit = "issues";
export const UnitPulls: Unit = "pulls";
export const UnitIssuesOrPulls: Unit = "issues|pulls";
export const UnitReleases: Unit = "releases";
export const UnitWiki: Unit = "wiki";
export const UnitExternalWiki: Unit = "ext_wiki";
export const UnitExternalTracker: Unit = "ext_issues";
export const UnitProjects: Unit = "projects";
export const UnitPackages: Unit = "packages";
export const UnitActions: Unit = "actions";
